- name: "Fact | download_dir"
  set_fact:
    download_dir: "{{ playbook_dir }}/.download"
  tags: ['always']

- name: "Assume .download directory does exist"
  file:
    path: "{{ download_dir }}"
    state: directory
  delegate_to: localhost
  tags: ['always']

- name: "Fact | environment_name"
  set_fact:
    environment_name: "{{ group_names[0] }}"

- name: "Fact | build_directory"
  set_fact:
    build_directory: "{{ playbook_dir }}/.build"

- name: "Fact | environment_build_directory"
  set_fact:
    environment_build_directory: "{{ build_directory }}/{{ environment_name }}"

- name: "Assume .build/.* directory for environment does exist"
  file:
    path: "{{ environment_build_directory }}"
    state: directory
  delegate_to: localhost

- name: "Fact | application_target_directory (if specified for web.directory)"
  set_fact:
    application_target_directory: "{{ web.directory }}"
  when: "web.directory is defined"

- name: "Fact | wordpress_target_directory (if specified)"
  set_fact:
    wordpress_target_directory: "{{ application_target_directory }}/wordpress"

- name: "Check installation status of wp-cli"
  shell:
    "which {{ tools.wpcli }}"
  register: r_wp_cli_status

- name: "Fail if wp-cli is not installed"
  fail:
    msg: "wp-cli not installed"
  when: r_wp_cli_status.rc != 0